/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Song;
import Controller.MusicController;
import java.nio.file.Files;
import java.nio.file.Paths;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author eston
 */
public class MainFrame extends javax.swing.JFrame {

    private Song[] songs;
    private MusicController musicController = new MusicController();
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        getContentPane().setBackground(
            new Color(21, 17, 23)
        );
        
        btnPlay.setEnabled(false);
        btnPause.setEnabled(false);
        btnStop.setEnabled(false);
        
        songs = new Song[] {
            new Song(
                "We Are The Champions",
                "src/resources/songs/song1.mp3",
                "src/resources/lyrics/song1.txt",
                "src/resources/images/song1.png"
            ),
            new Song(
                "Eye of the Tiger",
                "src/resources/songs/song2.mp3",
                "src/resources/lyrics/song2.txt",
                "src/resources/images/song2.png"
            ),
            new Song(
                "The Final Countdown",
                "src/resources/songs/song3.mp3",
                "src/resources/lyrics/song3.txt",
                "src/resources/images/song3.png"
            ),
            new Song(
                "Livin' on a Prayer",
                "src/resources/songs/song4.mp3",
                "src/resources/lyrics/song4.txt",
                "src/resources/images/song4.png"
            ),
            new Song(
                "Kung Fu Fighting",
                "src/resources/songs/song5.mp3",
                "src/resources/lyrics/song5.txt",
                "src/resources/images/song5.png"
            ),
            new Song(
                "Thriller",
                "src/resources/songs/song6.mp3",
                "src/resources/lyrics/song6.txt",
                "src/resources/images/song6.png"
            ),
            new Song(
                "Can't Help Falling in Love",
                "src/resources/songs/song7.mp3",
                "src/resources/lyrics/song7.txt",
                "src/resources/images/song7.png"
            ),
        };
        
        listSongs.setListData(songs);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listSongs = new javax.swing.JList<>();
        lblImage = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtLyrics = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnPause = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        lblNowPlaying = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Music Player");

        listSongs.setBackground(new java.awt.Color(45, 30, 38));
        listSongs.setBorder(null);
        listSongs.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        listSongs.setForeground(new java.awt.Color(255, 255, 255));
        listSongs.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listSongsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listSongs);

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/nosong.png"))); // NOI18N

        jScrollPane2.setBorder(null);

        txtLyrics.setEditable(false);
        txtLyrics.setBackground(new java.awt.Color(45, 30, 38));
        txtLyrics.setColumns(20);
        txtLyrics.setForeground(new java.awt.Color(255, 255, 255));
        txtLyrics.setRows(5);
        jScrollPane2.setViewportView(txtLyrics);

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 27)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Compact Music Player");

        jPanel1.setBackground(new java.awt.Color(21, 17, 23));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 16, 5));

        btnPause.setBackground(new java.awt.Color(102, 102, 102));
        btnPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/button_pause.png"))); // NOI18N
        btnPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPauseActionPerformed(evt);
            }
        });
        jPanel1.add(btnPause);

        btnPlay.setBackground(new java.awt.Color(153, 153, 255));
        btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/button_play.png"))); // NOI18N
        btnPlay.setMaximumSize(new java.awt.Dimension(64, 64));
        btnPlay.setMinimumSize(new java.awt.Dimension(64, 64));
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });
        jPanel1.add(btnPlay);

        btnStop.setBackground(new java.awt.Color(102, 102, 102));
        btnStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/button_stop.png"))); // NOI18N
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });
        jPanel1.add(btnStop);

        lblNowPlaying.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        lblNowPlaying.setForeground(new java.awt.Color(255, 255, 255));
        lblNowPlaying.setText("Now Playing: None");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNowPlaying)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblImage)
                                .addGap(30, 30, 30)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(lblNowPlaying)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblImage)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listSongsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listSongsValueChanged
        // TODO add your handling code here:
        Song chosenSong = listSongs.getSelectedValue();

        if (chosenSong != null) {
            btnPlay.setEnabled(true);
            btnStop.setEnabled(true);
            
            try {
                String lyrics =
                    Files.readString(
                        Paths.get(chosenSong.getLyricPath())
                    );
                txtLyrics.setText(lyrics);
                txtLyrics.setCaretPosition(0);
            } catch (Exception e) {
                txtLyrics.setText(
                    "Could not load lyrics."
                );

            }

            ImageIcon icon = new ImageIcon(chosenSong.getImagePath());

            Image scaledImage = icon.getImage().getScaledInstance(
                    145,   // width
                    145,   // height
                    Image.SCALE_SMOOTH
            );

            lblImage.setIcon(new ImageIcon(scaledImage));
            lblImage.setText( "" );
        }
    }//GEN-LAST:event_listSongsValueChanged

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // TODO add your handling code here:
        Song chosenSong = listSongs.getSelectedValue();

        if (chosenSong != null) {
            btnPause.setEnabled(true);
            lblNowPlaying.setText(
                "Now Playing: " + chosenSong.getTitle()
            );
            musicController.playSong(
                    chosenSong.getAudioPath()
            );
        }
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        // TODO add your handling code here:
        musicController.stopSong();
        btnPause.setEnabled(false);
        lblNowPlaying.setText("Now Playing: None");
    }//GEN-LAST:event_btnStopActionPerformed

    private void btnPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseActionPerformed
        // TODO add your handling code here:
        if (!musicController.isPaused()) {
            musicController.pauseSong();
        } else {
            musicController.resumeSong();
        }
    }//GEN-LAST:event_btnPauseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPause;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblNowPlaying;
    private javax.swing.JList<Song> listSongs;
    private javax.swing.JTextArea txtLyrics;
    // End of variables declaration//GEN-END:variables
}
