/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Song;
import Model.SongDAO;
import Controller.MusicController;
import java.nio.file.Files;
import java.nio.file.Paths;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author eston
 */
public class MainFrame extends javax.swing.JFrame {

    private Song[] songs;
    private MusicController musicController = new MusicController();
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        getContentPane().setBackground(
            new Color(21, 17, 23)
        );
        
        // pulls from music.db the list of tracks and their data (music, titles, lyrics, image)
        SongDAO songDAO = new SongDAO();
        java.util.List<Song> songList = songDAO.getAllSongs();
        songs = songList.toArray(new Song[0]);
        listSongs.setListData(songs);
        
        // initally disable all playback buttons
        btnPlay.setEnabled(false);
        btnPause.setEnabled(false);
        btnStop.setEnabled(false);
        
        // Autoplay handling
        musicController.setOnSongFinished(() -> {
            javax.swing.SwingUtilities.invokeLater(() -> {
                btnPause.setEnabled(false);

                if (chkAutoplay.isSelected()) {
                    playNextSong();
                }
            });
        });
        
        listSongs.setListData(songs);
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listSongs = new javax.swing.JList<>();
        lblImage = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtLyrics = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        btnPause = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        lblNowPlaying = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        chkAutoplay = new javax.swing.JCheckBox();
        btnAbout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Music Player");

        listSongs.setBackground(new java.awt.Color(45, 30, 38));
        listSongs.setBorder(null);
        listSongs.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        listSongs.setForeground(new java.awt.Color(255, 255, 255));
        listSongs.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listSongsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listSongs);

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/nosong.png"))); // NOI18N

        jScrollPane2.setBorder(null);

        txtLyrics.setEditable(false);
        txtLyrics.setBackground(new java.awt.Color(45, 30, 38));
        txtLyrics.setColumns(20);
        txtLyrics.setForeground(new java.awt.Color(255, 255, 255));
        txtLyrics.setRows(5);
        jScrollPane2.setViewportView(txtLyrics);

        jPanel1.setBackground(new java.awt.Color(21, 17, 23));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 12, 5));

        btnPause.setBackground(new java.awt.Color(102, 102, 102));
        btnPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/button_pause.png"))); // NOI18N
        btnPause.setBorderPainted(false);
        btnPause.setContentAreaFilled(false);
        btnPause.setFocusPainted(false);
        btnPause.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/button_pause_hover.png"))); // NOI18N
        btnPause.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/button_pause_clicked.png"))); // NOI18N
        btnPause.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/button_pause_clicked.png"))); // NOI18N
        btnPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPauseActionPerformed(evt);
            }
        });
        jPanel1.add(btnPause);

        btnPlay.setBackground(new java.awt.Color(153, 153, 255));
        btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/button_play.png"))); // NOI18N
        btnPlay.setBorderPainted(false);
        btnPlay.setContentAreaFilled(false);
        btnPlay.setFocusPainted(false);
        btnPlay.setMaximumSize(new java.awt.Dimension(64, 64));
        btnPlay.setMinimumSize(new java.awt.Dimension(64, 64));
        btnPlay.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/button_play_hover.png"))); // NOI18N
        btnPlay.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/button_play_clicked.png"))); // NOI18N
        btnPlay.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/button_play_clicked.png"))); // NOI18N
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });
        jPanel1.add(btnPlay);

        btnStop.setBackground(new java.awt.Color(102, 102, 102));
        btnStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/button_stop.png"))); // NOI18N
        btnStop.setBorderPainted(false);
        btnStop.setContentAreaFilled(false);
        btnStop.setFocusPainted(false);
        btnStop.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/button_stop_hover.png"))); // NOI18N
        btnStop.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/button_stop_clicked.png"))); // NOI18N
        btnStop.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/button_stop_clicked.png"))); // NOI18N
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });
        jPanel1.add(btnStop);

        lblNowPlaying.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        lblNowPlaying.setForeground(new java.awt.Color(255, 255, 255));
        lblNowPlaying.setText("Now Playing: None");

        jPanel2.setBackground(new java.awt.Color(21, 17, 23));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 25, 5));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 27)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Compact Music Player");
        jPanel2.add(jLabel1);

        chkAutoplay.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        chkAutoplay.setForeground(new java.awt.Color(255, 255, 255));
        chkAutoplay.setText("Autoplay Next Song");

        btnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/button_info.png"))); // NOI18N
        btnAbout.setBorder(null);
        btnAbout.setBorderPainted(false);
        btnAbout.setContentAreaFilled(false);
        btnAbout.setFocusPainted(false);
        btnAbout.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/button_info_hover.png"))); // NOI18N
        btnAbout.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/button_info_clicked.png"))); // NOI18N
        btnAbout.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/button_info_clicked.png"))); // NOI18N
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNowPlaying)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblImage)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(chkAutoplay))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAbout))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAbout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNowPlaying)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblImage))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkAutoplay)))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void playNextSong() {
        int currentIndex = listSongs.getSelectedIndex();
        
        if (currentIndex < songs.length - 1) {
            
            listSongs.setSelectedIndex(currentIndex + 1);
            Song nextSong = listSongs.getSelectedValue();
            musicController.playSong(nextSong.getAudioPath());
            
            btnPause.setEnabled(true);
            btnStop.setEnabled(true);           
        }
    }
      
    private void listSongsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listSongsValueChanged
        // TODO add your handling code here:
        Song chosenSong = listSongs.getSelectedValue();

        if (chosenSong != null) {
            btnPlay.setEnabled(true);
            btnStop.setEnabled(true);
            
            // Lyric output
            try {
                String lyrics =
                    Files.readString(
                        Paths.get(chosenSong.getLyricPath())
                    );
                txtLyrics.setText(lyrics);
                txtLyrics.setCaretPosition(0);
            } catch (Exception e) {
                txtLyrics.setText(
                    "Could not load lyrics."
                );

            }

            // Music image output
            ImageIcon icon = new ImageIcon(chosenSong.getImagePath());
            Image scaledImage = icon.getImage().getScaledInstance(
                    145,   // Image width
                    145,   // Image height
                    Image.SCALE_SMOOTH
            );

            lblImage.setIcon(new ImageIcon(scaledImage));
            lblImage.setText( "" );
        }
    }//GEN-LAST:event_listSongsValueChanged

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // TODO add your handling code here:
        Song chosenSong = listSongs.getSelectedValue();

        if (chosenSong != null) {
            btnPause.setEnabled(true);
            lblNowPlaying.setText(
                "Now Playing: " + chosenSong.getTitle()
            );
            musicController.playSong(
                    chosenSong.getAudioPath()
            );
        }
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        // TODO add your handling code here:
        musicController.stopSong();
        btnPause.setEnabled(false);
        lblNowPlaying.setText("Now Playing: None");
    }//GEN-LAST:event_btnStopActionPerformed

    private void btnPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseActionPerformed
        // TODO add your handling code here:
        if (!musicController.isPaused()) {
            musicController.pauseSong();
        } else {
            musicController.resumeSong();
        }
    }//GEN-LAST:event_btnPauseActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        // TODO add your handling code here:
        AboutFrame about = new AboutFrame();
        about.setLocationRelativeTo(this);
        about.setVisible(true);
    }//GEN-LAST:event_btnAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnPause;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnStop;
    private javax.swing.JCheckBox chkAutoplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblNowPlaying;
    private javax.swing.JList<Song> listSongs;
    private javax.swing.JTextArea txtLyrics;
    // End of variables declaration//GEN-END:variables
}
